name: Cypress Automation

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npx cypress verify

      - name: Run Cypress Tests
        # env:
        #   EMAIL: ${{ secrets.EMAIL }}
        #   PASSWORD: ${{ secrets.PASSWORD }}
        run: npx cypress run

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
         name: Cypress-HTML-Report
         path: cypress/reports/html/index.html

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Cypress-Screenshots
          path: cypress/screenshots